title = "TOML Example"

[general]
usecudnn = true
usecudnnbenchmark = true
gpuid = 1
loadpretrainedmodel = false
pretrainedmodelpath = "trainedmodel.pt"
savemodel = true
modelsavepath = "savedmodel.pt"

[input]
batchsize = 64
numworkers = 18
shuffle = true

[model]
type = "temp-conv"
inputdim = 256
hiddendim = 256
numclasses = 500
numlstms = 2

[training]
train = true
epochs = 30
startepoch = 0
statsfrequency = 1000
dataset = "/udisk/pszts-ssd/AV-ASR-data/BBC_Oxford/lipread_mp4"
learningrate = 0.003
momentum = 0.9
weightdecay = 0.0001

[validation]
validate = true
dataset = "/udisk/pszts-ssd/AV-ASR-data/BBC_Oxford/lipread_mp4"
saveaccuracy = true
accuracyfilelocation = "accuracy.txt"
