title = "TOML Example"

[general]
usecudnn = true
usecudnnbenchmark = true
load_pretrained_model = false
train_target = "frontend"
frontend_pretrained_model_path = "frontend_trained_model.pt"
savemodel = true

[input]
batchsize = 32
frameslen = 29
numworkers = 18
shuffle = true

[model]
type = "temp-conv"
inputdim = 256
hiddendim = 256
numclasses = 500
numlstms = 2

[training]
train = true
epochs = 30
startepoch = 0
statsfrequency = 1000
dataset = "./lipread_mp4"
learningrate = 0.003
momentum = 0.9
weightdecay = 0.0001

[validation]
validate = true
dataset = "./lipread_mp4"
saveaccuracy = true